---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: 160840381064.dkr.ecr.us-east-2.amazonaws.com/example-eks:625831a43ee449064901caf2d78b54de83b2cade
        #image: REGISTRY/IMAGE:TAG
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
